language: node_js

node_js:
  - 0.10

install:
  - npm install

before_script:
  - npm install -g grunt-cli

after_script:
  - ./scripts/bower/publish.sh

script:
  - grunt

env:
  global:
    - secure: hFfFJGwhQXEP+CTDT4Mn/rmkMvXSR1+vVPtPw7GtqAYh1x9Wi63enfsSRicvfOsY/6LjdZGmETSw2evY9a8f/tBUpXYk7GdHDEuwvh8/x89qvO2xBL8AhT/snvCpKS3CzxI8WF64xEE2QY+5nvogcFIBcHkIh1LIr0Fz4n91ZXs=
